# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js App CI Pipeline 

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  Code-Compile:
    runs-on: Agent1
  
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set-up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
  
      - name: Frontend Compilation
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +
      
      - name: Backend Compilation
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +
  
  Gitleaks-Scan:
    runs-on: Agent1
    needs: Code-Compile
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Clean temp files
        run: rm -f /tmp/gitleaks.tmp 
      - name: gitleaks setup
        uses: gitleaks/gitleaks-action@v2

      - name: gitleaks scan 
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
  
  Trivy_fs_scan:
    runs-on: Agent1
    needs: Gitleaks-Scan
  
    steps:
      - name: checkout code
        uses: actions/checkout@v4
  
      - name: trivy filesystem vulnerability scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  
  sonar-frontend:
    runs-on: Agent2
    needs: Trivy_fs_scan
    env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      
      - name: SonarQube scan (client)
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          projectBaseDir: client
          args: >
            -Dsonar.projectName=My_Project
            -Dsonar.projectKey=My_Project
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.verbose=true

      - name: Upload report-task.txt
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report-frontend
          path: client/.scannerwork/report-task.txt
        
  sonar-backend:
    runs-on: Agent2
    needs: sonar-frontend
    env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
     
      - name: SonarQube scan (api)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          jdkVersion: 21
          projectBaseDir: api
          args: >
            -Dsonar.projectName=My_Project
            -Dsonar.projectKey=My_Project
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.verbose=true
            -X

      - name: Upload report-task.txt
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report-backend
          path: api/.scannerwork/report-task.txt      
   
  SonarQube-Quality-GatesCheck-frontend:
    runs-on: Agent2
    needs: sonar-backend
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - name: Download report-task.txt
        uses: actions/download-artifact@v4
        with:
          name: sonar-report-frontend
          path: client/.scannerwork/
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: client/.scannerwork/report-task.txt
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Show Quality Gate Status
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
      - name: Fail if Quality Gate fails
        run: |
          if [ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]; then
            echo "Quality Gate failed"
            exit 1
          fi  
  
  SonarQube-Quality-GatesCheck-Backend:
    runs-on: Agent2
    needs: sonar-backend
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 
      - name: Download report-task.txt
        uses: actions/download-artifact@v4
        with:
          name: sonar-report-backend
          path: api/.scannerwork/
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: api/.scannerwork/report-task.txt
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Show Quality Gate Status
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
      - name: Fail if Quality Gate fails
        run: |
          if [ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]; then
            echo "Quality Gate failed"
            exit 1
          fi    
       
  Owasp-Dependency-Check-Frontend:
    runs-on: Agent2
    needs: SonarQube-Quality-GatesCheck-Backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cache dependency-check db
        uses: actions/cache@v4
        with:
          path: .dependency-check
          key: dependency-check-${{ runner.os }}

      - name: Create report directory
        run: mkdir -p reports

      - name: Run OWASP Dependency Check for Frontend
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/client \
            -v ${{ github.workspace }}/reports:/report \
            -v ${{ github.workspace }}/.dependency-check:/usr/share/dependency-check/data \
            owasp/dependency-check:9.0.9 \
            --project "my-app-frontend" \
            --scan /client \
            --format "HTML,JSON,SARIF" \
            --out /report \
            --failOnCVSS 9 \
            --nvdApiKey $NVD_API_KEY
            --nvdApiDelay 3000

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-frontend-report
          path: reports

      - name: upload sharif report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
  
  Owasp-Dependency-Check-Backend:
    runs-on: Agent2
    needs: Owasp-Dependency-Check-Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cache dependency-check db
        uses: actions/cache@v4
        with:
          path: .dependency-check
          key: dependency-check-${{ runner.os }}  

      - name: Create report directory
        run: mkdir -p reports

      - name: Run OWASP Dependency Check for Backend
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/api \
            -v ${{ github.workspace }}/reports:/report \
            -v ${{ github.workspace }}/.dependency-check:/usr/share/dependency-check/data \
            owasp/dependency-check:9.0.9 \
            --project "my-app-backend" \
            --scan /api \
            --format "HTML,JSON,SARIF" \
            --out /report \
            --failOnCVSS 9 \
            --nvdApiKey $NVD_API_KEY
            --nvdApiDelay 3000

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-backend-report
          path: reports

      - name: upload sharif report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
      
  Trivy_Config_Scan:
    runs-on: Agent1
    needs: Owasp-Dependency-Check-Backend
    steps:
      - name: checkout code
        uses: actions/chekout@v4
      - name: trivy-config-scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

          
  Build_backend_docker_image_scan_and_push:
    runs-on: Agent1
    needs: Trivy_Config_Scan
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: dockerhub login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      - name: Image Build (No Push)
        uses: docker/build-push-action@v7
        with:
          context: ./api
          file: ./api/Dockerfile
          push: false
          tags: swapnildocker23/backend:latest
          load: true
           
      - name: trivy image scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: image
          image-ref: swapnildocker23/backend:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: CRITICAL,HIGH

      - name: docker image push
        if: success()
        run: docker push swapnildocker23/backend:latest

  Build_frontend_docker_image_scan_and_push:
    runs-on: Agent1
    needs: Build_backend_docker_image_scan_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false
          tags: swapnildocker23/frontend:latest
          load: true

      - name: trivy image scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: image
          image-ref: swapnildocker23/frontend:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: CRITICAL,HIGH

      - name: docker image push
        if: success()
        run: docker push swapnildocker23/backend:latest

  Trivy_image_scan:
    runs-on: Agent1
    needs: Build_frontend_docker_image_scan_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Trivy image scan for backend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: swapnildocker23/backend:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Trivy image scan for frontend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: swapnildocker23/frontend:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

          
      
  
      
  
    
   
